In [2]:
import numpy as np
import tensorflow as tf

In [3]:
[1, 2, 3]

[1, 2, 3]

In [4]:
[[1,2,3],[4,5,6]]

[[1, 2, 3], [4, 5, 6]]

In [5]:
arr = np.array([1,2,3])

In [6]:
arr.shape

(3,)

In [7]:
arr = np.array([[1,2,3],[1,2,3]])

In [8]:
arr.shape

(2, 3)

In [9]:
tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [10]:
tf.constant(((1,2,3),(1,2,3)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3]])>

In [11]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [14]:
tensor = tf.constant(arr)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [15]:
tensor.shape

TensorShape([3])

In [16]:
tensor.dtype

tf.int32

In [19]:
tensor = tf.constant([1,2,3],dtype=tf.float32)
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [20]:
arr = np.array([1,2,3], dtype=np.float32)

In [21]:
arr.astype(np.uint8)

array([1, 2, 3], dtype=uint8)

In [22]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [23]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

In [24]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [25]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

In [26]:
type(tensor.numpy())

numpy.ndarray

In [27]:
type(tensor)

tensorflow.python.framework.ops.EagerTensor

In [28]:
np.random.randn(9)

array([-1.39950579, -1.90065683, -0.89038099,  1.46108845, -0.31772046,
        0.11813022,  1.16034182, -1.33119976, -0.18101987])

In [29]:
tf.random.normal([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.4150063 , -0.08858232,  1.6668459 ],
       [ 1.402602  , -0.43881127,  1.5573488 ],
       [-0.09790412,  0.50311536,  0.3593272 ]], dtype=float32)>

In [30]:
tf.random.uniform([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.21306384, 0.6686721 , 0.53496623, 0.24396586],
       [0.12663841, 0.89044964, 0.5415081 , 0.21232939],
       [0.00216925, 0.8736485 , 0.5818262 , 0.45049334],
       [0.24781907, 0.7548071 , 0.9326999 , 0.04425609]], dtype=float32)>